-- =====================================================================
-- Popula "Vagas" com os dados da planilha "VAGAS.xlsx" (aba "vagas
-- produção"). Rode no SQL Editor do Supabase, depois de já ter rodado o
-- schema.sql (precisa da tabela public.vagas).
--
-- 107 linhas transcritas da planilha. "Empresa" foi separado como coluna
-- própria porque a planilha original mistura duas empresas na mesma lista
-- (UPEXPRESS nas primeiras linhas, PRC a partir da linha marcada "PRC") —
-- as demais colunas (Área, Departamento, Setor, Cargo, Colaborador,
-- Observação, Aberto, Pendências) foram transcritas como estavam.
--
-- Deixei de fora da transcrição uma listinha solta de nomes ("líderes",
-- "Airton", "Barbara", "Diego", "Kelly", "Jose", "Marcos") e alguns valores
-- numéricos soltos que apareciam em colunas bem à direita da planilha,
-- sem relação clara com a linha em que estavam — se algum desses dados
-- for importante, me avise que eu incluo do jeito que você preferir.
-- =====================================================================

insert into public.vagas (empresa, area, departamento, setor, cargo, colaborador, observacao, aberto, pendencias, sort_order) values
  ('UPEXPRESS', null, null, null, 'Coordenador de PCP', null, null, true, false, 1),
  ('UPEXPRESS', 'TECIDOS E AVIAMENTOS', 'Estoque', 'TECIDOS E AVIAMENTOS', 'COORDENADOR DE ESTOQUE', 'DIEGO EDUARDO DE OLIVEIRA', null, false, false, 2),
  ('UPEXPRESS', 'ESTOQUE PECA PRONTA', 'Estoque', 'ESTOQUE PECA PRONTA', 'AUXILIAR DE ALMOXARIFADO', 'Carlos Eduardo ?', 'Vencimento o periodo de experiência   29/09 e o Carlos Eduardo é para repor', false, true, 3),
  ('UPEXPRESS', 'TECIDOS E AVIAMENTOS', 'Estoque', 'TECIDOS E AVIAMENTOS', 'AUXILIAR DE ALMOXARIFADO', 'DANILO', 'Separação de aviamento e lançamento de nota', false, false, 4),
  ('UPEXPRESS', 'TECIDOS E AVIAMENTOS', 'Estoque', 'TECIDOS E AVIAMENTOS', 'AUXILIAR DE ALMOXARIFADO', 'Bruno ?', 'Organização e revisão de tecido', false, true, 5),
  ('UPEXPRESS', 'TECIDOS E AVIAMENTOS', 'Estoque', 'TECIDOS E AVIAMENTOS', 'AUXILIAR DE ALMOXARIFADO', 'ROGERIO PAULO DOS SANTOS', 'Organização de tecido', true, true, 6),
  ('UPEXPRESS', 'TECIDOS E AVIAMENTOS', 'Estoque', 'TECIDOS E AVIAMENTOS', 'AUXILIAR DE ALMOXARIFADO', 'THIAGO MATHEUS DA SILVA OLIVEIRA', 'Organização e retirada de tecido', true, true, 7),
  ('UPEXPRESS', 'ESTOQUE PECA PRONTA', 'Estoque', 'ESTOQUE PECA PRONTA', 'AUXILIAR DE ALMOXARIFADO', 'JALLYZE MARIA MELGES', null, false, false, 8),
  ('UPEXPRESS', 'ESTOQUE PECA PRONTA', 'Estoque', 'ESTOQUE PECA PRONTA', 'AUXILIAR DE ALMOXARIFADO', 'Ana Paula', null, false, false, 9),
  ('UPEXPRESS', 'ESTOQUE PECA PRONTA', 'Estoque', 'ESTOQUE PECA PRONTA', 'AUXILIAR DE ALMOXARIFADO', 'ADRIAN TORRES MIRANDA', null, false, false, 10),
  ('UPEXPRESS', null, null, 'ESTOQUE PECA PRONTA', 'LÍDER DE ESTOQUE', 'JOSÉ RICARDO', 'INICIO 08/09', false, false, 11),
  ('UPEXPRESS', 'CORTE AUTOMATICO', 'Corte', 'CORTE AUTOMATICO', 'OPERADOR DE MAQUINA DE CORTE', 'EMILIA CRISPINO DA SILVA', null, false, false, 12),
  ('UPEXPRESS', 'CORTE MANUAL', 'Corte', 'CORTE MANUAL', 'CORTADOR (A)', 'ADRIANO FURTADO DE SOUZA', null, false, false, 13),
  ('UPEXPRESS', 'CORTE MANUAL', 'Corte', 'CORTE MANUAL', 'CORTADOR (A)', 'MAICON ANDRE DOMINGOS', null, false, false, 14),
  ('UPEXPRESS', 'ENFESTO AUTOMATICO', 'Corte', 'ENFESTO AUTOMATICO', 'LIDER DE CORTE', 'LUIS HENRIQUE FOGACA DE LIMA', null, false, false, 15),
  ('UPEXPRESS', 'ENFESTO MANUAL', 'Corte', 'ENFESTO MANUAL', 'ENFESTADOR(A)', 'KAROLINE OLIVEIRA DE PAULA', null, false, false, 16),
  ('UPEXPRESS', 'SEPARACAO DE CORTE', 'Corte', 'SEPARACAO DE CORTE', 'AUXILIAR DE PRODUCAO', 'kawana  21/8', null, false, false, 17),
  ('UPEXPRESS', 'SEPARACAO DE CORTE', 'Corte', 'SEPARACAO DE CORTE', 'AUXILIAR DE PRODUCAO', 'IZADORA DA SILVA RODRIGUES', null, false, false, 18),
  ('UPEXPRESS', 'CONCERTO', 'Corte', 'CORTE AUTOMATICO', 'OPERADOR DE MAQUINA DE CORTE', 'AILTON MOI JUNIOR', null, false, false, 19),
  ('UPEXPRESS', 'ENFESTO MANUAL', 'Corte', 'ENFESTO MANUAL', 'AUXILIAR DE PRODUCAO', 'Jhonatan Willian 24/8', null, false, false, 20),
  ('UPEXPRESS', 'CUSTOMIZACAO', 'Customizacao', 'CUSTOMIZACAO', 'AUXILIAR DE PRODUCAO', 'JULIA KLEIN SILVA LEAL', null, false, false, 21),
  ('UPEXPRESS', 'CUSTOMIZACAO', 'Customizacao', 'CUSTOMIZACAO', 'AUXILIAR DE PRODUCAO', 'LUCAS FELIPE DUARTE NICARETTO', null, false, false, 22),
  ('UPEXPRESS', 'CUSTOMIZACAO', 'Customizacao', 'CUSTOMIZACAO', 'Coordenador de customização', 'Bruno  entrada 06/10', null, true, false, 23),
  ('UPEXPRESS', 'CUSTOMIZACAO', 'Customizacao', 'CUSTOMIZACAO', 'AUXILIAR DE PRODUCAO', 'SAMANTHA', '15/09/2026', false, true, 24),
  ('UPEXPRESS', 'CUSTOMIZACAO', 'Customizacao', 'CUSTOMIZACAO', 'AUXILIAR DE PRODUCAO', '?', null, true, false, 25),
  ('UPEXPRESS', 'ESTAMPA DTF', 'Customizacao', 'ESTAMPA DTF', 'OPERADOR DE ESTAMPARIA', 'VICTORIA LETICIA DE MATOS', 'Alterar função', false, true, 26),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'LIDER DE PRODUCAO', 'ALINE BEZERRA BORGES', null, false, false, 27),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'OPERADOR DE MAQUINA DE BORDADO', 'ALEXANDRE RODRIGUES SOARES', null, false, false, 28),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'LIDER DE PRODUCAO', 'ALINE BEZERRA BORGES', null, false, false, 29),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'OPERADOR DE MAQUINA DE BORDADO', 'NESTOR FEDERICO ARANDA VARGAS', null, false, false, 30),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'OPERADOR DE MAQUINA DE BORDADO', 'GISLAINE CRISTINA DE ARAUJO', null, false, false, 31),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'OPERADOR DE MAQUINA DE BORDADO', 'GREICY DE SOUZA LEANDRO', null, false, false, 32),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'OPERADOR DE MAQUINA DE BORDADO', 'TAIS FERNANDA CARMO DE OLIVEIRA', null, false, false, 33),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'AUXILIAR DE PRODUCAO', 'JONATHAN FERNANDES DOS SANTOS', 'ALTERAR SETOR ?', false, true, 34),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'OPERADOR DE MAQUINA DE BORDADO', 'FABRICIO', '01/07/2026', false, false, 35),
  ('UPEXPRESS', 'BORDADO', 'Customizacao', 'BORDADO', 'OPERADOR DE MAQUINA DE BORDADO', 'Anenci', '07/07/2026', false, true, 36),
  ('UPEXPRESS', null, null, null, null, null, 'auxiliar de bordado com o Charles saindo, verificar se vai alterar em algo na produção do bordado', false, false, 37),
  ('UPEXPRESS', 'DISTRIBUICAO', 'Distribuicao', 'DISTRIBUICAO', 'COORDENADOR (A) DE COSTURA externa', 'Marcos Antônio Euzébio de Souza', null, false, false, 38),
  ('UPEXPRESS', 'DISTRIBUICAO', 'Distribuicao', 'DISTRIBUICAO', 'LIDER DE PRODUCAO', 'ANGELA APARECIDA PEREIRA', null, false, false, 39),
  ('UPEXPRESS', 'DISTRIBUICAO', 'Distribuicao', 'DISTRIBUICAO', 'COORDENADOR (A) DE COSTURA', 'BARBARA CRISTINA DA SILVA', null, false, false, 40),
  ('UPEXPRESS', 'REVISAO BORDADO E ESTAMPA', 'Revisao', 'REVISAO BORDADO E ESTAMPA', 'AUXILIAR DE QUALIDADE', 'MARINETE AGUIAR WILDNER', null, false, true, 41),
  ('UPEXPRESS', null, null, 'REVISAO BORDADO E ESTAMPA', 'AUXILIAR DE PRODUÇÃO', 'Jessica 25/8', null, false, false, 42),
  ('UPEXPRESS', 'TRIAGEM', null, null, null, 'JEFERSON', null, false, false, 43),
  ('UPEXPRESS', 'TRANSPORTE', 'Distribuicao', 'TRANSPORTE', 'MOTORISTA', 'JOAO RODRIGUES DE SOUZA', null, false, false, 44),
  ('UPEXPRESS', 'PREPARACAO', 'Preparacao', 'PREPARACAO', 'OPERADOR DE MAQUINA DE COSTURA', 'Erika 25/8', null, false, false, 45),
  ('UPEXPRESS', 'PREPARACAO', 'Preparacao', 'PREPARACAO', 'OPERADOR DE MAQUINA DE COSTURA', 'PATRICIA MARIA DOS SANTOS', null, false, false, 46),
  ('UPEXPRESS', 'PREPARACAO', 'Preparacao', 'PREPARACAO', 'OPERADOR DE MAQUINA DE COSTURA', 'Gisele 04/08  ?', null, false, false, 47),
  ('UPEXPRESS', 'PREPARACAO', 'Preparacao', 'PREPARACAO', 'OPERADOR DE MAQUINA DE COSTURA', 'Zeni 25/8', null, false, false, 48),
  ('UPEXPRESS', 'PREPARACAO', 'Preparacao', 'PREPARACAO', 'OPERADOR DE MAQUINA DE COSTURA', 'Luciana 25/8', null, false, false, 49),
  ('UPEXPRESS', 'PREPARACAO', 'Preparacao', 'PREPARACAO', 'OPERADOR DE MAQUINA DE COSTURA', 'Zenilda 25/8', null, true, false, 50),
  ('UPEXPRESS', 'PREPARACAO', 'Preparacao', 'PREPARACAO', 'Auxiliar de produção', 'Alice inicio  28/7', null, false, false, 51),
  ('UPEXPRESS', 'REVISAO PECA PRONTA', 'Revisao', 'REVISAO PECA PRONTA', 'AUXILIAR DE PRODUCAO', 'Emilly  08/09', 'Emilly  08/09', true, true, 52),
  ('UPEXPRESS', 'REVISAO PECA PRONTA', 'Revisao', 'REVISAO PECA PRONTA', 'AUXILIAR DE PRODUCAO', 'GABRIELA SANTOS DA SILVA', null, false, false, 53),
  ('UPEXPRESS', 'CONCERTO', 'Acabamento', 'Concerto', 'OPERADOR DE MAQUINA DE COSTURA', 'GLADYS CAROLINA VARGAS BENITEZ', null, true, false, 54),
  ('UPEXPRESS', 'ACABAMENTO', 'Acabamento', 'ACABAMENTO', 'OPERADOR DE MAQUINA DE ACABAMENTO', 'ANGELA REGINA TARDIM DA SILVA', null, false, false, 55),
  ('UPEXPRESS', 'ACABAMENTO', 'Acabamento', 'ACABAMENTO', 'OPERADOR DE MAQUINA DE COSTURA', 'CAMILA DE OLIVEIRA RAGGIOTTO DA SILVA', null, false, false, 56),
  ('UPEXPRESS', 'ACABAMENTO', 'Acabamento', 'ACABAMENTO', 'OPERADOR DE MAQUINA DE ACABAMENTO', 'PRISCILA ROBERTA GASPAR', null, false, false, 57),
  ('UPEXPRESS', 'ACABAMENTO', 'Acabamento', 'ACABAMENTO', 'OPERADOR DE MAQUINA DE ACABAMENTO', 'CAMILA ESTABILE 25/8', null, false, false, 58),
  ('UPEXPRESS', 'ACABAMENTO', 'Acabamento', 'ACABAMENTO', 'AUXILIAR DE PRODUCAO', 'Viviana 8/7', null, false, false, 59),
  ('UPEXPRESS', 'DOBRA E EMBALAGEM', 'Expedicao', '(REVISÃO ) DOBRA E EMBALAGEM', 'AUXILIAR DE EXPEDICAO', 'Micaelly 08/09', null, false, true, 60),
  ('UPEXPRESS', 'DOBRA E EMBALAGEM', 'Expedicao', 'DOBRA E EMBALAGEM', 'AUXILIAR DE EXPEDICAO', 'BRUNA SUELLEN VALIM MODOS', null, false, false, 61),
  ('UPEXPRESS', 'DOBRA E EMBALAGEM', 'Expedicao', 'DOBRA E EMBALAGEM', 'AUXILIAR DE EXPEDICAO', 'ROSILENI SCHICOVSKI', null, false, false, 62),
  ('UPEXPRESS', 'DOBRA E EMBALAGEM', 'Expedicao', 'DOBRA E EMBALAGEM', 'AUXILIAR DE PRODUCAO', 'DAIANE  18/8', null, false, false, 63),
  ('UPEXPRESS', 'EXPEDICAO', 'Expedicao', 'EXPEDICAO', 'EXPEDIDOR', 'GIVAILDA ALVES DE FREITAS FARIA', null, false, false, 64),
  ('UPEXPRESS', 'EXPEDICAO', 'Expedicao', 'EXPEDICAO', 'EXPEDIDOR', 'ROBSON ALEGRE GOUVEA', 'Matheus 25/8', true, false, 65),
  ('UPEXPRESS', 'EXPEDICAO', 'Expedicao', 'EXPEDICAO', 'EXPEDIDOR', 'APARECIDA DO CARMO OLIVEIRA', null, false, false, 66),
  ('UPEXPRESS', 'TRANSPORTE', 'Expedicao', 'TRANSPORTE', 'LIDER DE FROTA', 'ADENILTO APARECIDO DE OLIVEIRA', null, false, false, 67),
  ('UPEXPRESS', 'PILOTAGEM', 'Produto', 'PILOTAGEM', 'PILOTISTA', 'ANGELO AUGUSTO ACETI RUSSO', null, false, false, 68),
  ('UPEXPRESS', 'MODELAGEM', 'Produto', 'MODELAGEM', 'MODELISTA', 'EVILYN VIZOTTO', null, false, false, 69),
  ('UPEXPRESS', 'PRODUCAO', 'Pcp', 'PRODUCAO', 'GERENTE DE PRODUCAO', 'AIRTON RIBEIRO PEREIRA', null, false, false, 70),
  ('UPEXPRESS', 'CADASTRO DE PRODUTO', 'Produto', 'CADASTRO DE PRODUTO', 'ASSISTENTE DE PRODUTO', 'MARIANY DE SOUZA MOREIRA', null, false, false, 71),
  ('UPEXPRESS', 'ARTE FINALISTA', 'Produto', 'ARTE FINALISTA', 'ARTE FINALISTA', 'BIANCA OLIVEIRA DA SILVA', null, false, false, 72),
  ('UPEXPRESS', 'PCP', 'Pcp', 'PCP', 'ANALISTA DE PCP', 'GUSTAVO DA SILVA ZAVASKI', null, false, false, 73),
  ('UPEXPRESS', 'PCP', 'Pcp', 'PCP', 'ANALISTA DE PCP', 'JAQUELINE APARECIDA DA SILVA TOLOTO', null, false, false, 74),
  ('UPEXPRESS', 'COMPRAS', 'Compras', 'COMPRAS', 'ANALISTA DE COMPRAS', 'FERNANDA CRISTINA MOI', null, false, false, 75),
  ('UPEXPRESS', 'POS VENDA', 'Pcp', 'POS VENDA', 'ANALISTA COMERCIAL', 'LUCAS JARA CORDEIRO', null, false, false, 76),
  ('UPEXPRESS', 'A definir', 'A Definir', 'A definir', 'Sem lotacao', 'CAROLINA BUFFONI DE SOUZA', null, false, false, 77),
  ('UPEXPRESS', 'QUALIDADE', 'Qualidade', 'QUALIDADE', 'COORDENADOR (A) DE QUALIDADE', 'CRISTIANE MACHADO VIEIRA', null, false, false, 78),
  ('UPEXPRESS', 'QUALIDADE', 'Qualidade', 'QUALIDADE', 'ANALISTA DE CRONOANALISE', 'DEBORA VANESSA CRUZ MARTINS', null, false, false, 79),
  ('UPEXPRESS', 'A definir', 'A Definir', 'A definir', 'Sem lotacao', 'LEANDRO PALOZI DE OLIVEIRA JUNIOR', null, false, false, 80),
  ('PRC', null, 'Comercial', 'ATENDIMENTO DE FABRICA', 'ANALISTA COMERCIAL', 'ALINE MACORIS CORREA NARDIELLE ARAUJO', null, false, false, 81),
  ('PRC', null, 'Comercial', 'ATENDIMENTO DE FABRICA', 'ANALISTA COMERCIAL', 'IARA REGINA SALVI DE ASSIS', null, false, false, 82),
  ('PRC', null, 'Comercial', 'ATENDIMENTO DE FABRICA', 'ANALISTA COMERCIAL', 'ISABELA DOS SANTOS MARTINS', null, false, false, 83),
  ('PRC', null, 'Comercial', 'ATENDIMENTO DE FABRICA', 'ANALISTA COMERCIAL', 'NATHALIA BEATRIZ DA VEIGA FIGUEIREDO CAS', null, false, false, 84),
  ('PRC', null, 'Comercial', 'CRESCIMENTO COMERCIAL', 'EXECUTIVO DE VENDAS', 'FABIANA FRANCISCA DE SOUZA', null, false, false, 85),
  ('PRC', null, 'Comercial', 'CRESCIMENTO COMERCIAL', 'EXECUTIVO DE VENDAS', 'LIDIANE DO NASCIMENTO MARTINS', null, false, false, 86),
  ('PRC', null, 'Comercial', 'CRESCIMENTO COMERCIAL', 'EXECUTIVO DE VENDAS', 'LEOPOLDO ROHLING', null, false, false, 87),
  ('PRC', null, 'Comercial', 'COMERCIAL', 'EXECUTIVO DE VENDAS', 'REBECA COSTA MARINHO', null, false, false, 88),
  ('PRC', null, 'Comercial', 'COMERCIAL', 'EXECUTIVO DE VENDAS', 'Henrique  18/8', null, false, false, 89),
  ('PRC', null, 'Comercial', 'SUPORTE', 'ANALISTA COMERCIAL', 'ARYEGE HIKARI CUPERTINO ENDO', null, false, false, 90),
  ('PRC', null, 'Comercial', 'SUPORTE', 'ANALISTA COMERCIAL', '?', null, false, false, 91),
  ('PRC', null, 'Comercial', 'E-COMMERCE', 'ANALISTA DE E-COMMERCE', 'DENISE RIBEIRO', null, false, false, 92),
  ('PRC', null, 'Financeiro', 'FINANCEIRO', 'ANALISTA FINANCEIRO', 'HANNAH VIDO DA COSTA', null, false, false, 93),
  ('PRC', null, 'Departamento Geral', 'FINANCEIRO', 'ANALISTA FINANCEIRO', 'MONICA MARIA GOMES SILVA MOCO', null, false, false, 94),
  ('PRC', null, 'A Definir', 'A definir', 'Sem lotacao', 'SOLIANE APARECIDA RUIZ DE LIMA', null, false, false, 95),
  ('PRC', null, 'Rh', 'RH', 'ASSISTENTE DE RECURSOS HUMANOS', 'MARITYSSA RODRIGUES DE SOUSA', null, false, false, 96),
  ('PRC', null, 'Rh', 'RH', 'COORDENADOR (A) DE RH', 'VANESSA DE OLIVEIRA LACERDA', null, false, false, 97),
  ('PRC', null, 'Clube Uniforme', 'CLUBE UNIFORME', 'EXPEDIDOR', 'SILMARA MARQUES DE LIMA', null, false, false, 98),
  ('PRC', null, 'Clube Uniforme', 'ARTE FINALISTA', 'ARTE FINALISTA', 'WANESSA RODRIGUES DE SOUZA', null, false, false, 99),
  ('PRC', null, 'Clube Uniforme', 'SUPORTE LICENCIADOS', 'ASSISTENTE COMERCIAL', 'MARIANGELA DE SOUZA MEIRELES', null, false, false, 100),
  ('PRC', null, 'Clube Uniforme', 'MARKETING', 'ANALISTA DE MARKETING', 'Nathalia', null, false, false, 101),
  ('PRC', null, 'Clube Uniforme', 'SUPORTE LICENCIADOS', 'VENDEDORA', 'Victoria', null, false, false, 102),
  ('PRC', null, 'A Definir', 'A definir', 'Sem lotacao', 'MAGNO DE OLIVEIRA DA SILVA', null, false, false, 103),
  ('PRC', null, 'Clube Uniforme', 'COMERCIAL', 'GERENTE DE LOJA', 'SILVIO JEAN DA SILVA SEVILHERI', null, false, false, 104),
  ('PRC', null, 'Clube Uniforme', 'CUSTOMIZACAO', 'OPERADOR POLIVALENTE DA INDUSTRIA TEXTIL', 'LANA MORAIS SIMIONI', null, false, false, 105),
  ('PRC', null, 'Clube Uniforme', 'COMERCIAL', 'VENDEDOR(A)', 'GUSTAVO ANDRE GASPAR GONCALVES', null, false, false, 106),
  ('PRC', null, 'Clube Uniforme', 'LÍDER OPERACONAL', null, 'Giselle', null, false, false, 107);
